sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_8814c9d0d4d9_key -iv $encrypted_8814c9d0d4d9_iv -in multi-k8s-283410-aaff3dd2e0de.json.enc -out multi-k8s-283410-aaff3dd2e0de.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-283410
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials multi-cluster
